---
title: Sport Predictor Shiny App
author: Matthew Wankiewicz
date: '2021-11-01'
categories:
  - nba
  - nfl
tags:
  - shiny app
  - logistic regression
description: 'This is a shiny app I created to predict NBA games and various player stats for NBA and MLB players.'
---

This app uses logistic and linear regressions on various team's stats and determines the probability that the home team will win the game, and the difference in scores. For NBA games, I am using Four Factors stats, which are advanced stats that display a team's turnover, free throw, rebounding and scoring rates. 

There are also tabs for predicting an NBA player's stats vs a given team and a tab that predicts the number of strikeouts a pitcher will get in a start.

The NBA stat simulator uses 10000 Monte Carlo simulations on a player's average stats and then adjusts the value depending on how well the opponent would guard a player of the same position.

The strikeout simulator uses multiple models, including a Linear Mixed Effect model and Poisson model to predict how many strikeouts a player will get against a certain team. The output also includes the number of strikeouts that similar pitchers have gotten against opponents. For example, if we want to see how many strikeouts Kevin Gausman would get vs the Cubs, the page will return the average number of strikeouts recorded by players with similar strikeout and called strike + whiff percentages against Chicago.

```{r app, echo=FALSE}
knitr::include_app("https://wnkwz.shinyapps.io/predictors/")
```

